title: LoreHax
description: Some subtitle or description here
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/